#!/bin/bash

touch /var/www/html/storage/logs/php.log /var/www/html/storage/logs/laravel.log
chmod 777 /var/www/html/storage/logs/php.log /var/www/html/storage/logs/laravel.log

set +e

#Self signed certificates - autogenerated on every new container
if [ ! -f /etc/nginx/certs/server.key ]; then

  cp /etc/ssl_certs/openssl.cnf /etc/nginx/certs/server.cnf
  sed -i -e "s,DOMAIN_NAME,$DOMAIN_NAME,g" /etc/nginx/certs/server.cnf
  sed -i -e "s,HOSTNAME,$API_HOSTNAME,g" /etc/nginx/certs/server.cnf

  openssl genrsa -out /etc/nginx/certs/server.key 2048

  printf '\n\n\n\n\n' | openssl req -new -out /etc/nginx/certs/server.csr \
    -key /etc/nginx/certs/server.key \
    -config /etc/nginx/certs/server.cnf

  openssl x509 -req -sha256 -days 365 -in /etc/nginx/certs/server.csr \
    -signkey /etc/nginx/certs/server.key \
    -out /etc/nginx/certs/server.crt \
    -extensions v3_req \
    -extfile /etc/nginx/certs/server.cnf

fi

chmod 755 /etc/nginx/certs/*

# Adjust write permissions for www-data
cd /var/www/html
mkdir -p storage/framework/{session,views,cache}
chown -R www-data: storage

set -e

/usr/sbin/nginx -t

echo "STARTING PHP=FPM"
#######################################################################################################
# TO RUN AS ROOT: Edit etc_nginx_nginx.conf file, php_fpm_laravel.conf and supervisor_laravel.conf
# Comment the lines that run as www-data and uncomment the ones for root
# DON'T LET THIS GO TO PRODUCTION UNLESS REALLY NECESSARY
# Uncomment this line and comment the next too.
#/usr/sbin/php-fpm8.1 -R # THIS RUNS AS ROOT!!! Important if you want to have shelly.php
#######################################################################################################
/etc/init.d/php8.1-fpm start # That's the proper way if you want clear_env=no to work.

echo "STARTING NGINX"
nginx -g 'daemon on;'

echo "LET'S LOG!!!!"
echo "Booting at $(date)" >> /var/www/html/storage/logs/php.log
echo "Booting at $(date)" >> /var/www/html/storage/logs/laravel.log

# echo "STARTING CALMAV UPDATE DAEMON"
# echo "RUNNING AFTER NGINX"
# /usr/bin/freshclam
# /usr/bin/freshclam -d -c 6

tail -f /var/www/html/storage/logs/php.log /var/www/html/storage/logs/laravel.log > /dev/stdout
